version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run start:debug
    env_file:
      - ./api/.env
    depends_on:
      - postgres
    ports:
      - 9229:9229

  postgres:
    image: postgres:13
    env_file:
      - ./api/.env
    ports:
      - 35000:5432

  postgres_admin:
    restart: always
    image: dpage/pgadmin4:5.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    logging:
      driver: none
    ports:
      - 5050:5050

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3000:80
    depends_on:
      - api
